In [1]:
%cd ..

import builtins
builtins.uclresearch_topic = 'GIVENCHY' # 226984 entires
# builtins.uclresearch_topic = 'HAWKING' # 4828104 entries
# builtins.uclresearch_topic = 'NYC'
# builtins.uclresearch_topic = 'FLORIDA'
from configuration import config

import smtplib
import base64
from email.mime.text import MIMEText
from email.header import Header
from email.mime.multipart import MIMEMultipart
from email.mime.image import MIMEImage
from email.utils import COMMASPACE
import numpy as np
import pandas as pd
import pickle
import xgboost as xgb
import os
import os.path
import math
import sys
import csv
import matplotlib.pyplot as plt
from sklearn.externals import joblib
import scipy.integrate as spi
import pylab as pl
import networkx as nx
from tqdm import tqdm
import multiprocessing
from multiprocessing import Pool
from IPython.display import display

/home/ec2-user/May

/home/ec2-user/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/ec2-user/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

('Reading config file from location: '
 '/home/ec2-user/May/configuration/env.properties')
{'calculate': {'analysis': True,
               'network': True,
               'uniquetweets': True,
               'uniqueusers': True},
 'data': {'dates': ['2018-03-11', '2018-03-12', '2018-03-13'],
          'eventname': "Givenchy's Death",
          'phrases': ['givenchy%20death', 'givenchy%20passed%20away'],
          'starttime': 'Mar 12 08:20:00 -0500 2018'},
 'path': {'crawl': {'followers': '/home/ec2-user/May/followers',
                    'friends': '/home/ec2-user/May/friends'},
          'cwd': '/home/ec2-user/May/data/givenchy',
          'ml': '/home/ec2-user/May/data/givenchy/pickle',
          'networkx': {'all': '/home/ec2-user/May/data/givenchy/pickle/networkx_all.dat',
                       'friends': '/home/ec2-user/May/data/givenchy/pickle/networkx_friends.dat',
                       'potential': '/home/ec2-user/May/data/givenchy/pickle/networkx_potential.dat'},
          'pickle': {'exposed_user_ids_selected': '/home/ec2-user/May/data/givenchy/pickle/exposed_user_ids_selected.dat',
                     'followers': '/home/ec2-user/May/data/givenchy/pickle/followers.dat',
                     'followersneedcrawl': '/home/ec2-user/May/data/givenchy/pickle/followersneedcrawl.dat',
                     'friends': '/home/ec2-user/May/data/givenchy/pickle/friends.dat',
                     'infected_user_ids': '/home/ec2-user/May/data/givenchy/pickle/infected_user_ids.dat',
                     'needcrawl': '/home/ec2-user/May/data/givenchy/pickle/needcrawl.dat',
                     'network': '/home/ec2-user/May/data/givenchy/pickle/network.dat',
                     'tweets': '/home/ec2-user/May/data/givenchy/pickle/tweets.dat',
                     'users': '/home/ec2-user/May/data/givenchy/pickle/users.dat'},
          'result': '/home/ec2-user/May/data/givenchy/result',
          'twitter': '/home/ec2-user/May/data/givenchy/twitter'},
 'save_to_file': 'False',
 'timeframe': '1440'}

In [2]:
n_bytes = 2**31
max_bytes = 2**31 - 1

path = "/home/ec2-user/May/data/givenchy/pickle"  

def write_to_pickle(file_path, data):

    bytes_out = pickle.dumps(data)
    with open(file_path, 'wb') as f_out:
        for idx in range(0, n_bytes, max_bytes):
            f_out.write(bytes_out[idx:idx+max_bytes])

def load_pickle(file_path):
    bytes_in = bytearray(0)
    input_size = os.path.getsize(file_path)
    with open(file_path, 'rb') as f_in:
        for _ in range(0, input_size, max_bytes):
            bytes_in += f_in.read(max_bytes)
    return pickle.loads(bytes_in)

def loadModel(self):
    read_file = "data/" + self.model_name + ".dat"
    self.model = joblib.load(read_file)
    return self.model

# Load data

In [3]:
model = joblib.load(path+"/xgb_model_GIVENCHY (2).dat")
unique_users = load_pickle(path+"/80000users_3.pkl")
network = load_pickle(path+"/80000users_3.pkl")
users=load_pickle(path+'/Stanford_features.pkl')
betweenness =pd.read_csv('/home/ec2-user/May/data/centrality.csv')

In [4]:
unique_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70013 entries, 0 to 70012
Data columns (total 14 columns):
user_favourites_count               70013 non-null int64
followers_count                     70013 non-null int64
friends_count                       70013 non-null int64
user_id                             70013 non-null int64
user_listed_count                   70013 non-null int64
user_statuses_count                 70013 non-null int64
source_candidates                   70013 non-null object
infec_candidates                    70013 non-null object
user_created_days                   70013 non-null int64
normalized_user_statuses_count      70013 non-null float64
normalized_user_followers_count     70013 non-null float64
normalized_user_favourites_count    70013 non-null float64
normalized_user_listed_count        70013 non-null float64
normalized_user_friends_count       70013 non-null float64
dtypes: float64(5), int64(7), object(2)
memory usage: 7.5+ MB

In [5]:
# ######## infec_candidates ########
# temp=[]
# infec = [temp for i in range(len(unique_users))]
# unique_users["infec_candidates"]= None
# record_num = int(network.describe().iloc[0,0])

# for i in range(record_num):
#     source_candidates = unique_users.loc[i,'source_candidates']
#     #users.loc[i,"infec_candidates"] = list()
#     for j in range(len(source_candidates)):
#         candidates = source_candidates[j]
#         if infec[candidates] == []:
#             infec[candidates]=[i]
#         else :
#             infec[candidates]+=[i]

# unique_users.loc[:,"infec_candidates"]=infec

# unique_users.head()

# reprocess_data

In [6]:
def reprocess_data(time,origins,infectors,users,unique_users):
        i= int(users[users.user_id.isin([origins])].index.values)
        j= int(users[users.user_id.isin([infectors])].index.values)
        source_candidates = unique_users.loc[j,'source_candidates']
        sources = [x for x in source_candidates if users.loc[x,'TwM_time']<=time]
        sources_time=users[users.index.isin(sources)].sort_values(by=['TwM_time'])
        sources_dataframe = unique_users.loc[sources]
        timeList =  [users.loc[x].TwM_tCurrent - users.loc[x].TwM_time for x in sources]
        degreeList = list(unique_users.loc[k, 'followers_count'] + unique_users.loc[k, 'friends_count']  for k in sources)
    
            
        m=sources_time.index.values[0]
        n=sources_time.index.values[-1]
        
        users.loc[j,'UsM_deltaDays0'] = users.loc[m,'UsM_deltaDays']
        users.loc[j,'UsM_statusesCount0'] = users.loc[m,'UsM_statusesCount']
        users.loc[j,'UsM_followersCount0'] = users.loc[m,'UsM_followersCount']
        users.loc[j,'UsM_favouritesCount0'] = users.loc[m,'UsM_favouritesCount']
        users.loc[j,'UsM_friendsCount0']=users.loc[m,'UsM_friendsCount']
        users.loc[j,'UsM_listedCount0']=users.loc[m,'UsM_listedCount']
        users.loc[j,'UsM_normalizedUserStatusesCount0']=users.loc[m,'UsM_normalizedUserStatusesCount']
        users.loc[j,'UsM_normalizedUserFollowersCount0']=users.loc[m,'UsM_normalizedUserFollowersCount']
        users.loc[j,'UsM_normalizedUserFavouritesCount0']=users.loc[m,'UsM_normalizedUserFavouritesCount']
        users.loc[j,'UsM_normalizedUserListedCount0']=users.loc[m,'UsM_normalizedUserListedCount']
        users.loc[j,'UsM_normalizedUserFriendsCount0']=users.loc[m,'UsM_normalizedUserFriendsCount']
        
        users.loc[j,'UsM_deltaDays-1'] = users.loc[n,'UsM_deltaDays']
        users.loc[j,'UsM_statusesCount-1'] = users.loc[n,'UsM_statusesCount']
        users.loc[j,'UsM_followersCount-1']=users.loc[n,'UsM_followersCount']
        users.loc[j,'UsM_favouritesCount-1']=users.loc[n,'UsM_favouritesCount']
        users.loc[j,'UsM_friendsCount-1']=users.loc[n,'UsM_friendsCount']
        users.loc[j,'UsM_listedCount-1']=users.loc[n,'UsM_listedCount']
        users.loc[j,'UsM_normalizedUserStatusesCount-1']=users.loc[n,'UsM_normalizedUserStatusesCount']
        users.loc[j,'UsM_normalizedUserFollowersCount-1']=users.loc[n,'UsM_normalizedUserFollowersCount']
        users.loc[j,'UsM_normalizedUserFavouritesCount-1']=users.loc[n,'UsM_normalizedUserFavouritesCount']
        users.loc[j,'UsM_normalizedUserListedCount-1']=users.loc[n,'UsM_normalizedUserListedCount']
        users.loc[j,'UsM_normalizedUserFriendsCount-1']=users.loc[n,'UsM_normalizedUserFriendsCount']
        
       
        users.loc[j,'TwM_t0'] = users.loc[m].TwM_tCurrent - users.loc[m,'TwM_time']
        users.loc[j,'TwM_tSeed0'] = users.loc[m,'TwM_tSeed0']
        users.loc[j,'TwM_t-1'] = users.loc[m].TwM_tCurrent - users.loc[n,'TwM_time']
        users.loc[j,'TwM_tSeed-1'] = users.loc[n,'TwM_tSeed-1']
        users.loc[j,'TwM_tCurrent'] =  np.ceil(time/30)*30
        
        
        users.loc[j,'Nw_degree0'] = users.loc[m,'Nw_degree']
        users.loc[j,'Nw_degree-1'] = users.loc[n,'Nw_degree']
        users.loc[j,'Nw_inDegree0'] = users.loc[m,'UsM_friendsCount']
        users.loc[j,'Nw_inDegree-1'] = users.loc[n,'UsM_friendsCount']
        users.loc[j,'Nw_outDegree0'] = users.loc[m,'UsM_followersCount']
        users.loc[j,'Nw_outDegree-1'] = users.loc[n,'UsM_followersCount']
        users.loc[j,'Nw_degreeSeed0'] = users.loc[m,'Nw_degreeSeed0']
        users.loc[j,'Nw_inDegreeSeed0'] = users.loc[m,'Nw_inDegreeSeed0']
        users.loc[j,'Nw_outDegreeSeed0'] = users.loc[m,'Nw_outDegreeSeed0']
        users.loc[j,'Nw_degreeSeed-1'] = users.loc[n,'Nw_degreeSeed-1']
        users.loc[j,'Nw_inDegreeSeed-1'] = users.loc[n,'Nw_inDegreeSeed-1']
        users.loc[j,'Nw_outDegreeSeed-1'] = users.loc[n,'Nw_outDegreeSeed-1']
        
        
        
        users.loc[j,'SNw_generation0'] = users.loc[m,'SNw_generation']
        users.loc[j,'SNw_generation-1'] = users.loc[n,'SNw_generation']
        users.loc[j,'SNw_timeSinceSeed0'] = users.loc[m,'SNw_timeSinceSeed0']
        users.loc[j,'SNw_timeSinceSeed-1'] = users.loc[n,'SNw_timeSinceSeed-1']
        users.loc[j,'SNw_totalNodesInfected'] = infect_totalNodeInfected(users)
        users.loc[j,'SNw_nodeInfectedCentrality'] = len(sources)/users.loc[j,'SNw_totalNodesInfected']
        users.loc[j,'SNw_totalInDegree'] = infect_totalFriends(users)
        users.loc[j,'SNw_totalOutDegree'] = infect_totalFollowers(users)
        users.loc[j,'SNw_inDegreeCentrality'] = safe_division(in_degree[j], users.loc[j,'SNw_totalInDegree'])
        users.loc[j,'SNw_inDegreeCentrality0'] = users.loc[m,'SNw_inDegreeCentrality']
        users.loc[j,'SNw_inDegreeCentrality-1'] = users.loc[n,'SNw_inDegreeCentrality']
        users.loc[j,'SNw_outDegreeCentrality'] = safe_division(out_degree[j], users.loc[j,'SNw_totalOutDegree'])
        users.loc[j,'SNw_outDegreeCentrality0'] = users.loc[m,'SNw_outDegreeCentrality']
        users.loc[j,'SNw_outDegreeCentrality-1'] = users.loc[n,'SNw_outDegreeCentrality']
        users.loc[j,'SNw_inDegreeCentralitySeed0'] = users.loc[m,'SNw_inDegreeCentralitySeed0']
        users.loc[j,'SNw_outDegreeCentralitySeed0'] = users.loc[m,'SNw_outDegreeCentralitySeed0']
        users.loc[j,'SNw_inDegreeCentralitySeed-1'] = users.loc[n,'SNw_inDegreeCentralitySeed-1']
        users.loc[j,'SNw_outDegreeCentralitySeed-1'] = users.loc[n,'SNw_outDegreeCentralitySeed-1']


        users.loc[j,'SNw_nFriendsInfected']=len(sources)
        users.loc[j,'SNw_friendsInfectedRatio']=safe_division(len(sources), unique_users.loc[j,'friends_count'])
            
        users.loc[j,'Stat_average_kOut']=round(mean(degreeList), 1)
        users.loc[j,'Stat_average_t']=round(mean(timeList), 1)
        users.loc[j,'Stat_average_deltaDays']=sources_dataframe.user_created_days.mean()
        users.loc[j,'Stat_average_statusesCount']=sources_dataframe.user_statuses_count.mean()
        users.loc[j,'Stat_average_followersCount']=sources_dataframe.followers_count.mean()
        users.loc[j,'Stat_average_favouritesCount']=sources_dataframe.user_favourites_count.mean()
        users.loc[j,'Stat_average_friendsCount']=sources_dataframe.friends_count.mean()
        users.loc[j,'Stat_average_listedCount']=sources_dataframe.user_listed_count.mean()
        users.loc[j,'Stat_average_normalizedUserStatusesCount']=sources_dataframe.normalized_user_statuses_count.mean()
        users.loc[j,'Stat_average_normalizedUserFollowersCount']=sources_dataframe.normalized_user_followers_count.mean()
        users.loc[j,'Stat_average_normalizedUserFavouritesCount']=sources_dataframe.normalized_user_favourites_count.mean()
        users.loc[j,'Stat_average_normalizedUserListedCount']=sources_dataframe.normalized_user_listed_count.mean()
        users.loc[j,'Stat_average_normalizedUserFriendsCount']=sources_dataframe.normalized_user_friends_count.mean()
        if len(degreeList)!=0 :
            users.loc[j,'Stat_max_kOut']=max(degreeList) 
            users.loc[j,'Stat_min_kOut']=min(degreeList) 
        else:
            users.loc[j,'Stat_max_kOut']=''
            users.loc[j,'Stat_min_kOut']=''
#         temp = users[users.index.isin(['j'])]
        return users

In [7]:
# intervals = [60, 30, 15, 7]
intervals = [30]

# Helper function for mean value calculation
def mean(numbers):
    return float(sum(numbers)) / max(len(numbers), 1)

def safe_division(x, y):
    if y == 0:
        return 0
    else:
        return x/y
    
# infectedNetworkStats = {}
# for interval in intervals:
#     statsDictionary = {}
#     for timestamp in range(0, 24*60+1, interval):
#         infected_dataframe = unique_users[unique_users.time_lapsed <= timestamp]
#         statsDictionary[timestamp] = {}
#         statsDictionary[timestamp]['totalNodeInfected'] = infected_dataframe.shape[0]
#         statsDictionary[timestamp]['totalFollowers'] = sum(infected_dataframe.followers_count)
#         statsDictionary[timestamp]['totalFriends'] = sum(infected_dataframe.friends_count)
#     infectedNetworkStats[interval] = statsDictionary

def infect_totalNodeInfected(users):
    infected_dataframe = users[users.TwM_time>=0]
    states = infected_dataframe.shape[0]
    return states

def infect_totalFollowers(users):
    infected_dataframe = users[users.TwM_time>=0]
    states = sum(infected_dataframe.UsM_followersCount)
    return states

def infect_totalFriends(users):
    infected_dataframe = users[users.TwM_time>=0]
    states = sum(infected_dataframe.UsM_friendsCount)
    return states

in_degree = list(unique_users.friends_count)
out_degree = list(unique_users.followers_count)
degree = [sum(x) for x in zip(in_degree, out_degree)]

In [8]:
network_simulation = pd.DataFrame(columns=["t_current","user_id","source_candidates","infec_candidates",
                                           "followers_count","friends_count","source_id","seed_user_id",
                                           "SIR","generations","time_lapsed","time_since_seed"])
# network_simulation["user"] =unique_users["user"]
network_simulation["user_id"] = unique_users["user_id"]
network_simulation["source_candidates"] = unique_users["source_candidates"]
network_simulation["infec_candidates"] = unique_users["infec_candidates"]
network_simulation["followers_count"] = unique_users["followers_count"]
network_simulation["friends_count"] = unique_users["friends_count"]
#network_simulation.head()
# network_simualtion = load_pickle(path+'/Stanford_network_simulation_0.6.pkl')

In [9]:
##situation choose:
##a.全部为0   b.从0开始由小到大    c.从0开始由大到小

betweenness=betweenness.sort_values(by='betweenesscentrality')
betweenness=betweenness.iloc[len(betweenness)-5:len(betweenness)]
# betweenness
between_id =[x for x in betweenness['Id']]

seeds = network_simulation[network_simulation.user_id.isin(between_id)]
seeds['time_lapsed']=0
seeds

/home/ec2-user/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

,t_current,user_id,source_candidates,infec_candidates,followers_count,friends_count,source_id,seed_user_id,SIR,generations,time_lapsed,time_since_seed
451,NaN,15439395,"[479, 510, 482, 541, 493, 495, 507, 580, 536, ...","[452, 528, 490, 483, 517, 1198, 1156, 1312, 36...",12754295,50151,NaN,NaN,NaN,NaN,0,NaN
806,NaN,3359851,"[797, 834, 800, 819, 848, 822, 793, 829, 820, ...","[789, 828, 790, 799, 835, 791, 830, 796, 824, ...",503906,27988,NaN,NaN,NaN,NaN,0,NaN
1441,NaN,813286,"[1415, 1485, 1434, 1426, 1535, 1460, 1459, 153...","[1490, 1504, 1489, 758, 771, 1495, 4491, 4509,...",101454968,620510,NaN,NaN,NaN,NaN,0,NaN
2242,NaN,17093617,"[2241, 2261, 2220, 2277, 2270, 2297, 2319, 225...","[2212, 2229, 2243, 2285, 2218, 2362, 2213, 226...",7966561,1517036,NaN,NaN,NaN,NaN,0,NaN
10261,NaN,15846407,"[10143, 10123, 10128, 10199, 10233, 10192, 102...","[1441, 10238, 10169, 10245, 10279, 10306, 1032...",75965729,35685,NaN,NaN,NaN,NaN,0,NaN

In [10]:
### seeds ###
def seeds_setting_simulation(seeds,network_simulation):
    for i in range(len(seeds)):
        index = seeds.index.values
        network_simulation.loc[index,'SIR'] = 1
        network_simulation.loc[index,'generations'] = 0
        network_simulation.loc[index,'source_id'] = seeds.loc[index,'user_id']
        network_simulation.loc[index,'time_lapsed'] = seeds.loc[index,'time_lapsed']
        network_simulation.loc[index,'seed_user_id'] = seeds.loc[index,'user_id']
        network_simulation.loc[index,'time_since_seed'] = 0
    return network_simulation

def seeds_setting_features(seeds,users):
    for i in range(len(seeds)):

   
        j = seeds.index.values[i]
#         sources = [x for x in seeds.loc[j,'source_candidates']]
        users.loc[j,'UsM_deltaDays0'] = users.loc[j,'UsM_deltaDays']
        users.loc[j,'UsM_statusesCount0'] = users.loc[j,'UsM_statusesCount']
        users.loc[j,'UsM_followersCount0']=users.loc[j,'UsM_followersCount']
        users.loc[j,'UsM_favouritesCount0']=users.loc[j,'UsM_favouritesCount']
        users.loc[j,'UsM_friendsCount0']=users.loc[j,'UsM_friendsCount']
        users.loc[j,'UsM_listedCount0']=users.loc[j,'UsM_listedCount']
        users.loc[j,'UsM_normalizedUserStatusesCount0']=users.loc[j,'UsM_normalizedUserStatusesCount']
        users.loc[j,'UsM_normalizedUserFollowersCount0']=users.loc[j,'UsM_normalizedUserFollowersCount']
        users.loc[j,'UsM_normalizedUserFavouritesCount0']=users.loc[j,'UsM_normalizedUserFavouritesCount']
        users.loc[j,'UsM_normalizedUserListedCount0']=users.loc[j,'UsM_normalizedUserListedCount']
        users.loc[j,'UsM_normalizedUserFriendsCount0']=users.loc[j,'UsM_normalizedUserFriendsCount']
        
        users.loc[j,'UsM_deltaDays-1'] = users.loc[j,'UsM_deltaDays']
        users.loc[j,'UsM_statusesCount-1'] = users.loc[j,'UsM_statusesCount']
        users.loc[j,'UsM_followersCount-1']=users.loc[j,'UsM_followersCount']
        users.loc[j,'UsM_favouritesCount-1']=users.loc[j,'UsM_favouritesCount']
        users.loc[j,'UsM_friendsCount-1']=users.loc[j,'UsM_friendsCount']
        users.loc[j,'UsM_listedCount-1']=users.loc[j,'UsM_listedCount']
        users.loc[j,'UsM_normalizedUserStatusesCount-1']=users.loc[j,'UsM_normalizedUserStatusesCount']
        users.loc[j,'UsM_normalizedUserFollowersCount-1']=users.loc[j,'UsM_normalizedUserFollowersCount']
        users.loc[j,'UsM_normalizedUserFavouritesCount-1']=users.loc[j,'UsM_normalizedUserFavouritesCount']
        users.loc[j,'UsM_normalizedUserListedCount-1']=users.loc[j,'UsM_normalizedUserListedCount']
        users.loc[j,'UsM_normalizedUserFriendsCount-1']=users.loc[j,'UsM_normalizedUserFriendsCount']
        
        users.loc[j,'TwM_t0'] =seeds.loc[j,'time_lapsed']
        users.loc[j,'TwM_t-1'] =seeds.loc[j,'time_lapsed']
        users.loc[j,'TwM_tCurrent'] = np.ceil(seeds.loc[j,'time_lapsed']+0.001/30)*30   
        users.loc[j,'TwM_tSeed0'] = seeds.loc[j,'time_lapsed']                         
        users.loc[j,'TwM_tSeed-1'] = seeds.loc[j,'time_lapsed']
        users.loc[j,'TwM_time'] = seeds.loc[j,'time_lapsed']

        users.loc[j,'Nw_degree0'] = users.loc[j,'Nw_degree']
        users.loc[j,'Nw_degree-1'] = users.loc[j,'Nw_degree']
        users.loc[j,'Nw_inDegree0'] = users.loc[j,'UsM_friendsCount']
        users.loc[j,'Nw_inDegree-1'] = users.loc[j,'UsM_friendsCount']
        users.loc[j,'Nw_outDegree0'] = users.loc[j,'UsM_followersCount']
        users.loc[j,'Nw_outDegree-1'] = users.loc[j,'UsM_followersCount']
        users.loc[j,'Nw_degreeSeed0'] = users.loc[j,'Nw_degree']    
        users.loc[j,'Nw_inDegreeSeed0'] = users.loc[j,'UsM_friendsCount'] 
        users.loc[j,'Nw_outDegreeSeed0'] = users.loc[j,'UsM_followersCount']
        users.loc[j,'Nw_degreeSeed-1'] = users.loc[j,'Nw_degree']
        users.loc[j,'Nw_inDegreeSeed-1'] = users.loc[j,'UsM_friendsCount']
        users.loc[j,'Nw_outDegreeSeed-1'] = users.loc[j,'UsM_followersCount']
        
        users.loc[j,'SNw_generation0'] = 0
        users.loc[j,'SNw_generation-1'] = 0
        users.loc[j,'SNw_generation'] = 0
        users.loc[j,'SNw_totalNodesInfected'] = infect_totalNodeInfected(users)
#         users.loc[j,'SNw_nodeInfectedCentrality'] = len(sources)/users.loc[j,'SNw_totalNodesInfected']
        users.loc[j,'SNw_totalInDegree'] = infect_totalFriends(users)
        users.loc[j,'SNw_totalOutDegree'] = infect_totalFollowers(users)
        users.loc[j,'SNw_inDegreeCentrality'] = safe_division(in_degree[j], users.loc[j,'SNw_totalInDegree'])
        users.loc[j,'SNw_inDegreeCentrality0'] = users.loc[j,'SNw_inDegreeCentrality']
        users.loc[j,'SNw_inDegreeCentrality-1'] = users.loc[j,'SNw_inDegreeCentrality']
        users.loc[j,'SNw_outDegreeCentrality'] = safe_division(out_degree[j], users.loc[j,'SNw_totalOutDegree'])
        users.loc[j,'SNw_outDegreeCentrality0'] = users.loc[j,'SNw_outDegreeCentrality']
        users.loc[j,'SNw_outDegreeCentrality-1'] = users.loc[j,'SNw_outDegreeCentrality']
        users.loc[j,'SNw_inDegreeCentralitySeed0'] = users.loc[j,'SNw_inDegreeCentrality']               
        users.loc[j,'SNw_outDegreeCentralitySeed0'] = users.loc[j,'SNw_outDegreeCentrality']                
        users.loc[j,'SNw_inDegreeCentralitySeed-1'] = users.loc[j,'SNw_inDegreeCentrality']                  
        users.loc[j,'SNw_outDegreeCentralitySeed-1'] = users.loc[j,'SNw_outDegreeCentrality']
    return users

In [11]:
seeds_setting_simulation(seeds,network_simulation)
seeds_setting_features(seeds,users)

,label,UsM_deltaDays,UsM_statusesCount,UsM_followersCount,UsM_favouritesCount,UsM_friendsCount,UsM_listedCount,UsM_normalizedUserStatusesCount,UsM_normalizedUserFollowersCount,UsM_normalizedUserFavouritesCount,...,Stat_average_friendsCount,Stat_average_listedCount,Stat_average_normalizedUserStatusesCount,Stat_average_normalizedUserFollowersCount,Stat_average_normalizedUserFavouritesCount,Stat_average_normalizedUserListedCount,Stat_average_normalizedUserFriendsCount,Stat_max_kOut,Stat_min_kOut,user_id
0,NaN,2679,201,2090,548,46,65,0.075028,0.780142,0.204554,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,214328887
1,NaN,3246,5695,305257,38,181,4929,1.75447,94.041,0.0117067,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34428380
2,NaN,3417,5124,11756,31,498,93,1.49956,3.44044,0.00907229,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17116707
3,NaN,3266,35499,57992,4449,1482,894,10.8693,17.7563,1.36222,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28465635
4,NaN,2359,20720,15033,1968,219,45,8.78338,6.37262,0.834252,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380580781
5,NaN,3344,14602,284075,2158,68,1934,4.36663,84.9507,0.645335,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18996905
6,NaN,2660,6933,2121,309,206,12,2.60639,0.797368,0.116165,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,221036078
7,NaN,2834,807,4710,74,35,49,0.284757,1.66196,0.0261115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,153460275
8,NaN,2970,3021,11627,350,934,63,1.01717,3.91481,0.117845,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107830991
9,NaN,3385,4153,16996,9,552,238,1.22688,5.02097,0.00265879,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17868918
10,NaN,2840,28375,41712,3588,198,521,9.9912,14.6873,1.26338,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,151338729
11,NaN,2657,6187,5399,140,512,11,2.32857,2.03199,0.052691,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222261763
12,NaN,3330,41876,669869,7119,600,4741,12.5754,201.162,2.13784,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19705747
13,NaN,3047,3918,20883,1300,834,1638,1.28585,6.85363,0.426649,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88323281
14,NaN,3325,3755,652,24,120,13,1.12932,0.19609,0.00721805,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19933035
15,NaN,2844,14109,17797,630,255,334,4.96097,6.25774,0.221519,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149538028
16,NaN,2820,45088,14488,503,3531,158,15.9887,5.13759,0.178369,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158419434
17,NaN,3403,25245,57400,2110,212,1424,7.41845,16.8675,0.620041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17434613
18,NaN,2835,6954,13085,941,28,100,2.45291,4.61552,0.331922,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,153226312
19,NaN,2386,36605,537,628,252,17,15.3416,0.225063,0.263202,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,364971269
20,NaN,2994,6324,3444,109,11,18,2.11222,1.1503,0.0364061,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100581193
21,NaN,3118,58248,40064,17894,967,488,18.6812,12.8493,5.73894,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69592091
22,NaN,2744,45369,10803,728,182,209,16.5339,3.93695,0.265306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187773078
23,NaN,2318,5869,3616,208,268,12,2.53192,1.55997,0.0897325,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,406628822
24,NaN,2253,1650,237,10,68,7,0.732357,0.105193,0.00443853,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,460282402
25,NaN,2527,21513,32706,218,124,132,8.51326,12.9426,0.0862683,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,280935165
26,NaN,2279,13066,1627,6,328,2,5.73322,0.71391,0.00263273,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,437804658
27,NaN,3270,6343,29557,80,233,254,1.93976,9.03884,0.0244648,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27633075
28,NaN,2518,995,3700,2,59,12,0.395155,1.46942,0.000794281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,285312927
29,NaN,2893,3730,11273,13,134,57,1.28932,3.89665,0.00449361,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131613362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69983,NaN,2802,26620,281,150,719,47,9.50036,0.100286,0.0535332,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165153568
69984,NaN,3153,29664,445,903,273,9,9.40818,0.141135,0.286394,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59953940
69985,NaN,3165,9203,163,52,280,33,2.90774,0.0515008,0.0164297,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56222976
69986,NaN,2810,40274,355,5100,172,1,14.3324,0.126335,1.81495,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162157731
69987,NaN,2838,5971,193,105,7,4,2.10395,0.0680056,0.0369979,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152011250
69988,NaN,2884,7345,121,0,220,7,2.54681,0.0419556,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134894667
69989,NaN,3268,25546,997,5871,288,25,7.81701,0.30508,1.79651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28016093
69990,NaN,2876,11844,1353,83,178,6,4.11822,0.470445,0.0288595,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137772184
69991,NaN,2432,8733,202,7,199,0,3.59087,0.0830592,0.00287829,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336218834
69992,NaN,2853,46595,1709,172,234,6,16.3319,0.599019,0.0602874,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146229554
69993,NaN,2608,21840,527,559,194,17,8.37423,0.202071,0.21434,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,240895600
69994,NaN,3187,29129,175,332,94,9,9.13994,0.0549106,0.104173,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49037471
69995,NaN,2765,75641,713,987,543,24,27.3566,0.257866,0.356962,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179167773
69996,NaN,2586,23173,184,105,271,5,8.96094,0.0711524,0.0406032,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250733287
69997,NaN,2525,13325,18654,1,152,42,5.27723,7.38772,0.00039604,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,281765007
69998,NaN,2842,27701,2447,74,378,0,9.74701,0.861013,0.026038,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150319193
69999,NaN,2667,103934,734,3194,384,162,38.9704,0.275216,1.1976,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,218640513
70000,NaN,3147,32466,845,2974,1011,23,10.3165,0.26851,0.945027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61497784
70001,NaN,3141,29069,320353,4405,1444,827,9.2547,101.991,1.40242,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63135128
70002,NaN,2697,20442,103,39,191,33,7.57953,0.0381906,0.0144605,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,206918348
70003,NaN,3024,75980,359,3157,680,146,25.1257,0.118717,1.04398,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93641182
70004,NaN,3173,34220,454,42,361,258,10.7847,0.143082,0.0132367,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53811382
70005,NaN,3190,3278,319075,2,308,2134,1.02759,100.024,0.000626959,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48108211
70006,NaN,2391,58419,453,366,104,3,24.4329,0.18946,0.153074,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,362077620
70007,NaN,2801,11526,346,397,50,156,4.11496,0.123527,0.141735,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165498547
70008,NaN,2581,106839,1028,9469,571,176,41.3944,0.398295,3.66873,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,253509115
70009,NaN,3139,27074,427,3181,336,42,8.62504,0.136031,1.01338,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63784655
70010,NaN,3140,103166,432,2170,106,124,32.8554,0.13758,0.691083,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63503127
70011,NaN,3095,22950,448,484,479,0,7.41519,0.14475,0.156381,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75829996
70012,NaN,2847,26536,161,12,59,3,9.32069,0.0565508,0.00421496,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,148563360

In [12]:
network_simulation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70013 entries, 0 to 70012
Data columns (total 12 columns):
t_current            0 non-null object
user_id              70013 non-null int64
source_candidates    70013 non-null object
infec_candidates     70013 non-null object
followers_count      70013 non-null int64
friends_count        70013 non-null int64
source_id            5 non-null object
seed_user_id         5 non-null object
SIR                  5 non-null object
generations          5 non-null object
time_lapsed          5 non-null object
time_since_seed      5 non-null object
dtypes: int64(3), object(9)
memory usage: 6.4+ MB

In [15]:

def simulation(t,unique_users,network_simulation):
    for i in range(len(unique_users)):
        if np.isnan(network_simulation.loc[i,"time_lapsed"]) == False :
            if round(network_simulation.loc[i,"time_lapsed"]) <= t:
                infec_candidates=network_simulation.loc[i,"infec_candidates"]

                for j in range(len(infec_candidates)):
                    infector = network_simulation.loc[i,"infec_candidates"][j]

                    if network_simulation.loc[infector,'SIR']!=1 :
                        user_id1 = network_simulation.loc[i,'user_id']
                        user_id2 = network_simulation.loc[infector,'user_id']
                        processed_user=reprocess_data(t+1,user_id1,user_id2,users,unique_users)

                        valid = processed_user[processed_user.index.isin([infector])]
#                             print(valid['Stat_average_t'])
                        valid = valid.drop(['label','user_id','SNw_generation','TwM_time'],axis=1)

                        valid = valid.astype('float64')

                        columns = list(valid.columns)
                        X = valid[columns]
                        pre_data = xgb.DMatrix(X)
                        infec = model.predict(pre_data)
#                         print(infec)
                        if infec>0.8 :
                            users.loc[infector,'TwM_time'] = t
                            network_simulation.loc[infector,"SIR"] = 1
                            network_simulation.loc[infector,"generations"] = network_simulation.loc[i,"generations"]+1
                            network_simulation.loc[infector,"source_id"] = network_simulation.loc[i,"user_id"] 
                            network_simulation.loc[infector,"seed_user_id"] = network_simulation.loc[i,"seed_user_id"] 
                            network_simulation.loc[infector,"time_lapsed"] = t+1
            #             network_simulation.loc[i,"SIR"]=2 
    return unique_users,network_simulation

In [ ]:
##time = 5*60 minutes with resuming, due to releasing memory
for t in range(0,6):
    temp_data=simulation(t,unique_users,network_simulation)
    unique_users = temp_data[0]
    network_simulation = temp_data[1]
    print(t)
    write_to_pickle(path+'/Stanford_network_simulation_betweenness_5.pkl', network_simulation)

# for t in range(10,20):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(20,30):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(30,40):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(40,50):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(50,60):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(70,80):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(90,100):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(110,120):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(120,130):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(130,140):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(140,150):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(150,160):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(160,170):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(170,180):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(180,190):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(190,200):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(210,220):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(220,230):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(230,240):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(240,250):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(250,260):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(260,270):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(270,280):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(280,290):
#     temp_data=simulation(t,unique_users,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

# for t in range(290,300):
#     temp_data=simulation(t,unique_us01ers,network_simulation)
#     unique_users = temp_data[0]
#     network_simulation = temp_data[1]
#     print(t)
#     write_to_pickle(path+'/Stanford_network_simulation_0.6.pkl', network_simulation)

0
1
2

In [ ]:
network_simulation["t_current"]=users["TwM_tCurrent"]
# network_simulation

In [19]:
# network_simulation[network_simulation.generations.isin([0])]
x=[0,1,2,3,4,5]
network_simulation[network_simulation.generations.isin([5])]

# network_simulation.info()

,t_current,user_id,source_candidates,infec_candidates,followers_count,friends_count,source_id,seed_user_id,SIR,generations,time_lapsed,time_since_seed
8,NaN,107830991,"[10, 61, 35, 28, 41, 56, 52, 3, 49, 113, 69, 9...","[9, 58, 20, 77, 54, 6, 31, 43, 165, 21, 153, 3...",11627,934,151338729,3359851,1,5,5,NaN
25,NaN,280935165,"[20, 96, 18, 58, 111, 156, 69, 90, 59, 38, 76,...","[26, 42, 44, 122, 165, 72, 32, 70, 94, 22, 13,...",32706,124,314316607,3359851,1,5,5,NaN
35,NaN,67864340,"[10, 117, 135, 82, 15, 18, 97, 44, 37, 84, 62,...","[36, 39, 79, 41, 4, 8, 56, 13, 81, 2, 93, 38, ...",6794,211,151338729,3359851,1,5,5,NaN
37,NaN,270449528,"[47, 113, 14, 97, 42, 103, 43, 87, 6, 112, 22,...","[38, 32, 36, 9, 39, 96, 127, 93, 16, 44, 94, 6...",30427,972,151338729,3359851,1,5,5,NaN
46,NaN,206923844,"[52, 77, 105, 156, 60, 113, 138, 96, 62, 18, 3...","[47, 51, 149, 55, 145, 6, 137, 192, 59, 70, 93...",19913,89,151338729,3359851,1,5,5,NaN
148,NaN,265077741,"[113, 61, 62, 10, 88, 173, 2, 83, 70, 90, 111,...","[94, 6, 72, 33, 58, 3, 34, 0, 32, 122, 135, 27...",637,715,151338729,3359851,1,5,5,NaN
165,NaN,204140367,"[25, 21, 8, 83, 173, 111, 140, 103, 47, 163, 9...","[86, 42, 41, 74, 34, 127, 75, 28, 27, 26, 69, ...",13881,935,151338729,3359851,1,5,5,NaN
192,NaN,273149543,"[46, 97, 76, 137, 86, 18, 54, 105, 156, 111, 1...",[],1267,0,151338729,3359851,1,5,5,NaN
195,NaN,72680406,"[222, 200, 214, 204, 231, 202, 229, 230]","[196, 224, 209, 254, 240, 255, 203, 249]",12676,462,83876527,15439395,1,5,5,NaN
205,NaN,22689667,"[204, 244, 202, 268, 235, 196, 230, 255, 238, ...","[264, 220, 240, 201, 203, 225, 211, 224, 54986...",3489,429,83876527,15439395,1,5,5,NaN
207,NaN,4126501,"[251, 227, 231, 214, 229]","[208, 219, 245, 254, 263, 200, 228, 206, 223, ...",146800,1351,46073276,17093617,1,5,5,NaN
208,NaN,22558481,"[207, 214]","[213, 206, 252, 229, 228, 216]",20194,2890,46073276,17093617,1,5,5,NaN
223,NaN,28359405,"[213, 216, 214, 229, 207, 231, 246, 254, 250, ...","[200, 226, 202]",404297,441,46073276,17093617,1,5,5,NaN
235,NaN,9503302,"[221, 204, 268, 240, 238, 260, 201, 211, 224]","[212, 237, 205, 218]",483,300,16858804,15846407,1,5,5,NaN
252,NaN,50944856,"[248, 253, 208, 217, 214, 227, 216, 226, 251]","[219, 206, 245]",665633,185,46073276,17093617,1,5,5,NaN
254,NaN,23150071,"[207, 214, 255, 195]","[202, 233, 271, 231, 248, 247, 200, 223, 249, ...",3621,2263,46073276,17093617,1,5,5,NaN
266,NaN,20583098,"[240, 220, 230, 259, 6539, 54995, 41654, 54990...","[238, 260, 224, 197, 54986]",456,395,37977732,3359851,1,5,5,NaN
280,NaN,291476217,"[214, 231]",[],11021,71,46073276,17093617,1,5,5,NaN
1738,NaN,75260121,"[10, 37, 18492, 18464, 18444, 18442, 28606]","[1735, 94, 72, 84, 1, 58, 4159, 135, 33, 165, 81]",1022,908,151338729,3359851,1,5,5,NaN
18476,NaN,15186688,"[18475, 18445, 18528, 122, 9, 18526, 61, 35, 2...","[39, 93, 4225, 58, 1, 18184, 18509, 84, 81, 14...",15012,503,133055665,3359851,1,5,5,NaN
18500,NaN,131029775,"[37, 18507, 18466, 18494, 54, 41, 18482, 18442...","[18475, 18506, 47, 18453, 35, 18534, 18520, 77...",5193,2129,314316607,3359851,1,5,5,NaN
18512,NaN,479751714,"[10, 33]","[25, 72, 39, 18480, 18454, 62, 18469, 18460, 5...",118,159,151338729,3359851,1,5,5,NaN
18898,NaN,43001357,"[94, 10, 18529, 63356, 63386, 18444, 9251, 633...","[29, 72, 1739, 4159, 1801, 4114, 1, 147, 6964,...",842,244,151338729,3359851,1,5,5,NaN
28586,NaN,43837009,"[18464, 18, 112, 83, 70, 22775, 2, 37, 105, 41...","[38, 25, 18493, 22778, 18463, 18497, 15, 47, 2...",5916,309,151338729,3359851,1,5,5,NaN
28613,NaN,233385634,"[18497, 94, 18, 22769, 96, 77, 18464, 0, 41, 4...","[18444, 5, 32, 58, 83, 84, 21679, 47, 13, 42, ...",1604,277,314316607,3359851,1,5,5,NaN
34905,NaN,18005241,"[34836, 34815, 34842, 10, 34814]","[34906, 16991, 34857, 40, 14975, 34813, 34833,...",5613,7977,151338729,3359851,1,5,5,NaN
36228,NaN,422224303,"[59, 36227, 140, 70, 10, 18480, 18496, 37, 15,...","[5, 32, 18454, 27, 94, 155, 135, 33, 1, 11, 22...",11509,330,151338729,3359851,1,5,5,NaN
36231,NaN,395559648,"[10, 41, 28609, 46, 69, 0, 37, 3, 137, 18, 54,...","[22778, 22769, 9, 100, 140, 16, 1, 18479, 2170...",7089,401,151338729,3359851,1,5,5,NaN
36251,NaN,28076725,[122],"[36252, 36233, 36241, 36232]",121639,1635,133055665,3359851,1,5,5,NaN
37357,NaN,149508095,"[18442, 115, 10, 37358, 21, 33, 68, 18469, 97,...","[135, 75, 18480, 58, 1, 94, 125, 84, 72, 63356...",1982,326,151338729,3359851,1,5,5,NaN
37809,NaN,159662936,"[10, 135, 37831]","[1, 37835, 36963, 3432, 27, 22782, 3924, 14978...",379,239,151338729,3359851,1,5,5,NaN
37827,NaN,140448388,"[33, 37810, 18534, 18477, 36240, 37855, 37785,...","[18503, 37802, 72, 58, 122, 4634, 37794, 37852...",14338,457,151338729,3359851,1,5,5,NaN
38913,NaN,217786405,"[28580, 34136, 10]","[149, 37, 21689, 58, 28595, 27, 155, 18483, 22...",1415,835,151338729,3359851,1,5,5,NaN
40738,NaN,190572817,"[40748, 18464, 40746, 18893, 40757, 135, 37787...","[28585, 21, 23, 40754, 40751, 18477, 28574, 39...",1122,824,314316607,3359851,1,5,5,NaN
40742,NaN,523885474,"[135, 77, 10, 18460, 165, 54, 36227, 94, 37861...","[68, 155, 22800, 29, 27, 25, 18533, 40739, 32,...",2779,294,151338729,3359851,1,5,5,NaN
41471,NaN,354733764,"[18464, 18468, 21679, 41491, 94, 18454, 41455,...","[41472, 41483, 21, 41481, 41453, 37356, 51, 72...",2153,121,151338729,3359851,1,5,5,NaN
44392,NaN,158699598,"[33, 18492, 28606, 10, 18464]","[12, 41, 28594, 44415, 18444, 14882, 122, 3783...",1456,805,151338729,3359851,1,5,5,NaN
44404,NaN,261702903,"[32, 33, 28594, 28606, 18483, 18480, 18444, 13...","[15, 94, 70, 53, 28, 9, 83, 75, 18505, 1, 84, ...",612,37,151338729,3359851,1,5,5,NaN
46834,NaN,146232050,"[18483, 10, 49, 94, 15, 37, 18444, 46851, 4683...","[72, 135, 1, 122, 27, 9, 39, 18479, 29, 18466,...",3260,293,151338729,3359851,1,5,5,NaN
50641,NaN,321086857,"[37620, 50646, 20, 22780, 50627, 40742, 38872,...","[51, 18497, 122, 27, 22766, 21703, 58, 46, 84,...",3840,353,314316607,3359851,1,5,5,NaN
55035,NaN,30701628,"[15126, 54985, 54994, 236, 41654, 54987, 54995...",[],569,33,5533902,3359851,1,5,5,NaN
56059,NaN,129679987,"[1, 122, 165, 39, 18497, 135, 33, 56055]","[51, 18184, 4634, 20894, 72, 14849, 6265, 84]",2532,177,133055665,3359851,1,5,5,NaN
61110,NaN,72168943,[10],"[18471, 18505, 18492, 61083, 3924, 27, 14888, ...",447,350,151338729,3359851,1,5,5,NaN
61821,NaN,16007812,"[239, 61918, 61875, 61890, 41893]","[8563, 17993, 30475, 38229, 61896, 21539, 61884]",9459,2003,98976495,3359851,1,5,5,NaN
61979,NaN,16414371,"[33437, 122, 4159, 57809, 22814, 37850, 21701,...","[39, 84, 93, 18476, 51, 1, 4634, 72, 81, 14849...",1415,121,133055665,3359851,1,5,5,NaN

In [ ]:
write_to_pickle(path+'/Stanford_network_simulation_betweenness_5.pkl', network_simulation)

In [ ]:
# network_simulation